#!/bin/bash

echo -e "=============================================================================="
echo -e "Sr. No.\t Command\t Comment"
echo -e "------\t----------\t----------------------"
echo -e "1\t id++ id--\t variable post-increment and post-decrement"
echo -e "2\t ++id --id\t variable pre-increment and pre-decrement"
echo -e "3\t + -\t\t unary minus and plus"
echo -e "4\t ! ~\t\t logical and bitwise negation"
echo -e "5\t **\t\t exponentiation"
echo -e "6\t * / %\t\t exponentiation"
echo -e "7\t + -\t\t addition, subtraction"
echo -e "8\t << >>\t\t left and right bitwise shifts"
echo -e "9\t <= >= < >\t comparison"
echo -e "10\t == !=\t\t equality and inequality"
echo -e "11\t &\t\t bitwise AND"
echo -e "12\t ^\t\t bitwise exclusice OR"
echo -e "13\t |\t\t bitwise OR"
echo -e "14\t &&\t\t logical AND"
echo -e "15\t ||\t\t logical OR"
echo -e "16\t expr?expr:expr\t conditional operator"
echo -e "17\t = *= /= %= += -="
echo -e "\t <<= >>= &= ^= |=\t assignment"
echo -e "18\t expr1 , expr2\t comma"
echo -e "=============================================================================="
